documentation:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - pyproject.toml
          - .github/**/*

tests:
  - changed-files:
      - any-glob-to-any-file:
          - tests/**/*

source:
  - changed-files:
      - any-glob-to-any-file:
        - src/**/*
