# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.0

jobs:
  update_playlists:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "main.py" }}
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies
      - run:
          name: Install dependencies
          command: |
            if [ ! -f ~/venv/bin/activate ]; then
              python3 -m venv ~/venv
              source ~/venv/bin/activate
              pip install -r requirements.txt
            fi
      - run:
          name: Run main script
          command: |
            source ~/venv/bin/activate
            python3 ./main.py
      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "main.py" }}
          paths:
            - ~/venv
            - ~/project/cache_persist

workflows:
  version: 2
  commit-workflow:
    jobs:
      - update_playlists
  scheduled-workflow:
    triggers:
      - schedule:
          # every day at 4am AEST, 6pm (18:00) UTC
          cron: "0 18 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update_playlists
