version: 2.1

orbs:
  # orb docs: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.2

workflows:
  # workflow docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  commit-update:
    jobs:
      - update-playlists
  scheduled-update:
    triggers:
      - schedule:
          # every day at 4am AEST, 6pm (18:00) UTC
          cron: "0 18 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update-playlists

jobs:
  update-playlists:
    # Docker executor docs: https://circleci.com/docs/2.0/executor-types/
    # CircleCI Docker images: https://circleci.com/developer/images/image/cimg/python
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-playlists-{{ checksum "poetry.lock" }}
            - v1-playlists
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: coverage run -m unittest
      - run:
          name: Create coverage report
          command: coverage report -m
      - run:
          name: Update playlists
          command: |
            python ./music_playlists/main.py
      - save_cache:
          key: v1-playlists-{{ checksum "poetry.lock" }}
          paths:
            - ~/project/music_playlists/cache_persist
